In [39]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
src = r'D:\++PROJECT++\DATASETS\sony_RS\\'

### Data exploration

In [11]:
df_contents = pd.read_csv(src+r'content.csv')
df_users = pd.read_csv(src+r'user.csv')
df_rel = pd.read_csv(src+r'relationship.csv')

In [13]:
print(len(df_contents))
df_contents.head()

48645


content_id content_type language    genre  duration release_date  \
0   cont_475_19_32       series  english    drama   4980000   2018-07-01   
1  cont_2185_15_21       series  english    drama   3000000   2016-03-29   
2  cont_4857_13_28       series    tamil   comedy   3120000   2006-03-06   
3    cont_3340_1_5       sports    hindi  cricket   9900000   2009-01-10   
4  cont_1664_10_29       series    hindi   action   3660000   2020-05-25   

   rating  episode_count  season_count  
0      10             32            19  
1       4             21            15  
2       8             28            13  
3       0              5             1  
4       2             29            10

In [20]:
print(len(df_users))
df_users['gender'].replace(to_replace = 'M', value = 1, inplace = True)
df_users['gender'].replace(to_replace = 'F', value = 0, inplace = True)
df_users.head()

13843


user_id  user_age  gender        location joining_date
0  user_45028@domain.com        40       1             Goa   2018-06-18
1  user_95235@domain.com        55       0  Andhra Pradesh   2019-09-17
2  user_44289@domain.com        38       0             Goa   2018-09-03
3  user_23708@domain.com        47       0     West Bengal   2020-11-15
4  user_40584@domain.com        24       1      Tamil Nadu   2018-02-06

In [17]:
print(len(df_rel))
df_rel.head()

1654450


user_id      content_id  duration        date start_time  \
0  user_44902@domain.com  cont_1718_16_7   1920000  2020-06-17   06:19:13   
1  user_87018@domain.com    cont_825_1_3   1080000  2019-12-06   19:58:14   
2  user_53430@domain.com  cont_1981_2_26    180000  2020-07-27   01:52:51   
3  user_53696@domain.com  cont_1072_18_7   1440000  2021-08-24   06:34:14   
4  user_80251@domain.com   cont_760_9_27    960000  2020-06-15   16:57:19   

   end_time  
0  06:51:13  
1  20:16:14  
2  01:55:51  
3  06:58:14  
4  17:13:19

### Pre-processing
- Creating the inference table

In [30]:
locations = list(set(df_users['location'].values.tolist()))
print(locations)
loc_rep = {}
for index, i in enumerate(locations):
    loc_rep[i] = index
df_users['location'].replace(to_replace = loc_rep, inplace = True)

['Tamil Nadu', 'Meghalaya', 'Manipur', 'Telangana', 'Punjab', 'Haryana', 'Himachal Pradesh', 'Madhya Pradesh', 'Goa', 'Mizoram', 'Bihar', 'Gujarat', 'Assam', 'Chhattisgarh', 'Odisa', 'Jharkhand', 'Tripura', 'Delhi', 'Kerala', 'Uttar Pradesh', 'Karnataka', 'Rajasthan', 'Maharashtra', 'Arunachal Pradesh', 'West Bengal', 'Uttarakhand', 'Sikkim', 'Nagaland', 'Andhra Pradesh']


***
#### Need to update location codes by distance between the location, capturing regional content

In [69]:
## updating joining date with timestamp
df_users['joining_date'] = df_users['joining_date'].apply(lambda x: datetime.timestamp(datetime.strptime(str(x).strip(), '%Y-%m-%d'))) 

In [71]:
ss = df_users.loc[:,['user_age','gender','location','joining_date']].to_numpy()

In [72]:
print(ss)

[[4.0000000e+01 1.0000000e+00 8.0000000e+00 1.5292602e+09]
 [5.5000000e+01 0.0000000e+00 2.8000000e+01 1.5686586e+09]
 [3.8000000e+01 0.0000000e+00 8.0000000e+00 1.5359130e+09]
 ...
 [1.9000000e+01 0.0000000e+00 9.0000000e+00 1.5672762e+09]
 [5.2000000e+01 1.0000000e+00 1.8000000e+01 1.5796314e+09]
 [1.9000000e+01 1.0000000e+00 5.0000000e+00 1.5945786e+09]]
